package com.example.huayeloltool.enums;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Heros {
    AATROX(266, "暗裔剑魔"),
    AATROX1(893, "双界灵兔"),
    THRESH(412, "魂锁典狱长"),
    TRYNDAMERE(23, "蛮族之王"),
    GRAGAS(79, "酒桶"),
    CASPIOPIA(69, "魔蛇之拥"),
    AURELION_SOL(136, "铸星龙王"),
    RYZE(13, "符文法师"),
    POPPY(78, "波比"),
    SION(14, "亡灵战神"),
    ANNIE(1, "安妮"),
    JHIN(202, "戏命师"),
    KARMA(43, "天启者"),
    NAUTILUS(111, "深海泰坦"),
    KLED(240, "诺克萨斯统领"),
    LUX(99, "光辉女郎"),
    AHRI(103, "九尾妖狐"),
    OLAF(2, "奥拉夫"),
    VIKTOR(112, "机械先驱"),
    ANIVIA(34, "冰晶凤凰"),
    SINGED(27, "炼金术士"),
    GAREN(86, "德玛西亚之力"),
    LISSANDRA(127, "冰霜女巫"),
    MAOKAI(57, "扭曲树精"),
    MORGANA(25, "堕落天使"),
    EVELYNN(28, "寡妇制造者"),
    FIZZ(105, "潮汐海灵"),
    HEIMERDINGER(74, "海默丁格"),
    ZED(238, "影流之主"),
    RUMBLE(68, "机械公敌"),
    MORDEKAISER(82, "铁铠冥魂"),
    SONA(37, "琴瑟仙女"),
    KOG_MAW(96, "深渊巨口"),
    KATARINA(55, "不祥之刃"),
    LULU(117, "仙灵女巫"),
    ASHE(22, "寒冰射手"),
    KARTHUS(30, "死亡颂唱者"),
    ALISTAR(12, "牛头酋长"),
    DARIUS(122, "诺克萨斯之手"),
    VAYNE(67, "暗夜猎手"),
    VARUS(110, "复仇之矛"),
    UDYR(77, "兽灵行者"),
    LEONA(89, "曙光女神"),
    JAYCE(126, "未来守护者"),
    SYNDRA(134, "暗黑元首"),
    PANTHEON(80, "战争之王"),
    RIVEN(92, "放逐之刃"),
    KHA_ZIX(121, "虚空掠夺者"),
    CORKI(42, "英勇投弹手"),
    AZIR(268, "沙漠皇帝"),
    CAITLYN(51, "皮城女警"),
    NIDALEE(76, "狂野女猎手"),
    KENNEN(85, "凯南"),
    GALIO(3, "加里奥"),
    VEIGAR(45, "邪恶小法师"),
    BARD(432, "巴德"),
    GNAR(150, "迷失之牙"),
    MALZAHAR(90, "虚空先知"),
    GRAVES(104, "法外狂徒"),
    VI(254, "皮城执法官"),
    KAYLE(10, "审判天使"),
    IREILIA(39, "刀锋意志"),
    LEE_SIN(64, "盲僧"),
    ILLAOI(420, "深海泰坦"),
    ELISE(60, "蜘蛛女皇"),
    VOLIBEAR(106, "雷霆咆哮"),
    NUNU(20, "雪人骑士"),
    TWISTED_FATE(4, "卡牌大师"),
    JAX(24, "武器大师"),
    SHYVANA(102, "龙血武姬"),
    KALISTA(429, "复仇之矛"),
    DR_MUNDO(36, "蒙多医生"),
    IVERN(427, "翠神"),
    DIANA(131, "皎月女神"),
    TAHM_KENCH(223, "河流之王"),
    BRAND(63, "复仇焰魂"),
    SEJUANI(113, "北地之怒"),
    VLADIMIR(8, "猩红收割者"),
    ZAC(154, "生化魔人"),
    REK_SAI(421, "虚空遁地兽"),
    QUINN(133, "法外狂徒"),
    AKALI(84, "阿卡丽"),
    TALIYAH(163, "岩雀"),
    TRISTANA(18, "麦林炮手"),
    HECARIM(120, "亡灵战神"),
    SIVIR(15, "赏金猎人"),
    LUCIAN(236, "圣枪游侠"),
    RENGAR(107, "傲之追猎者"),
    WARWICK(19, "嗜血猎手"),
    SKARNER(72, "水晶先锋"),
    MALPHITE(54, "熔岩巨兽"),
    YASUO(157, "疾风剑豪"),
    XERATH(101, "远古巫灵"),
    TEEMO(17, "提莫"),
    NASUS(75, "荒漠屠夫"),
    RENEKTON(58, "沙漠死神"),
    DRAVEN(119, "荣耀行刑官"),
    SHACO(35, "恶魔小丑"),
    SWAIN(50, "乌鸦"),
    TALON(91, "泰隆"),
    JANNA(40, "风暴之怒"),
    ZIGGS(115, "爆破鬼才"),
    EKKO(245, "时间刺客"),
    ORIANNA(61, "发条魔灵"),
    FIORA(114, "无双剑姬"),
    FIDDLESTICKS(9, "末日使者"),
    CHO_GATH(31, "虚空恐惧"),
    RAMMUS(33, "披甲龙龟"),
    LEBLANC(7, "诡术妖姬"),
    SORAKA(16, "众星之子"),
    ZILEAN(26, "时光守护者"),
    NOCTURNE(56, "永恒梦魇"),
    JINX(222, "暴走萝莉"),
    YORICK(83, "牧魂人"),
    URGOT(6, "厄加特"),
    KINDRED(203, "牧魂人"),
    MISS_FORTUNE(21, "赏金猎人"),
    WUKONG(62, "齐天大圣"),
    BLITZCRANK(53, "蒸汽机器人"),
    SHEN(98, "慎"),
    BRAUM(201, "布隆"),
    XIN_ZHAO(5, "德邦总管"),
    TWITCH(29, "瘟疫之源"),
    MASTER_YI(11, "无极剑圣"),
    TARIC(44, "宝石骑士"),
    AMUMU(32, "阿木木"),
    GANGPLANK(41, "海洋之灾"),
    TRUNDLE(48, "巨魔之王"),
    KASSADIN(38, "虚空行者"),
    VEL_KOZ(161, "虚空之眼"),
    ZYRA(143, "荆棘之兴"),
    NAMI(267, "唤潮鲛姬"),
    JARVAN_IV(59, "德玛西亚皇子"),
    EZREAL(81, "探险家伊泽瑞尔");

    private final int id;
    private final String name;

    public static String getNameById(int id) {
        for (Heros hero : values()) {
            if (hero.id == id) {
                return hero.name;
            }
        }
        return null;
    }
}